name: XRAY_MEGA_CHECKER_100K
on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 240 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests[socks]

      - name: Install Xray
        run: |
          VERSION=$(curl -s https://api.github.com/repos/XTLS/Xray-core/releases/latest | grep tag_name | cut -d '"' -f 4)
          wget "https://github.com/XTLS/Xray-core/releases/download/${VERSION}/Xray-linux-64.zip"
          unzip -o Xray-linux-64.zip
          chmod +x xray

      - name: Run MEGA Checker
        run: python3 checker.py

      - name: Push results to repository
        run: |
          git config --global user.name "Xray-Mega-Bot"
          git config --global user.email "mega-bot@vpn.com"
          git add working.txt whitelist.txt sub.txt
          git commit -m "Update: $(date +'%Y-%m-%d %H:%M:%S') [100k Check]" || exit 0
          git push
