name: XRAY_FARM_HOURLY
on:
  schedule:
    - cron: '0 * * * *' # Каждый час
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: pip install requests[socks]
      - name: Install Xray
        run: |
          VERSION=$(curl -s https://api.github.com/repos/XTLS/Xray-core/releases/latest | grep tag_name | cut -d '"' -f 4)
          wget "https://github.com/XTLS/Xray-core/releases/download/${VERSION}/Xray-linux-64.zip"
          unzip Xray-linux-64.zip
          chmod +x xray
      - name: Run Farm
        run: python3 checker.py
      - name: Push Results
        run: |
          git config --global user.name "XrayBot"
          git config --global user.email "bot@xray.com"
          git add working.txt whitelist.txt sub.txt
          git commit -m "Update: $(date)" || exit 0
          git push
